wechat_service/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about_us'

  get 'home/contact_us'

  devise_for :users, class_name: "User"

  resources :apps
  resources :key_words
  resources :users
  resources :files
  resources :messages do
    collection do
      get 'all'
      post 'send_message'
    end
  end

  match 'wechat/:id' => 'wx#index', via: [:get, :post]
  match 'weixin_app' => 'wx#index', via: [:get, :post]

  root 'home#index'
end

wechat_service/app/models/message.rb
class Message < ActiveRecord::Base
end

wechat_service/app/controllers/messages_controller.rb
# encoding: utf-8
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    app = App.find(params[:app_id])
    @wx_users = app.wx_users
  end

  def all
    app = current_user.apps.find(params[:app_id])
    messages = app.messages.where('from_user_name = ? or to_user_name = ?', params[:user_open_id], params[:user_open_id])

    render json: {code: 1, messages: messages}
  end

  def send_message
    app = current_user.apps.find(params[:app_id])
    message = Wx::Common.build_text_message(params[:user_open_id], params[:message])
    save_message(message, app)
    logger.debug Time.now.to_f
    response = Wx::Api.send_message(app, message)
    logger.debug Time.now.to_f
    code = response['errcode'] == 0 ? 1 : 0

    render json: {code: code}
  end

  def save_message(message_hash, app)
    message = Message.new
    message.title          = ''
    message.content        = message_hash['text']['content']
    message.original       = message_hash.to_json
    message.message_type   = 'text'
    message.to_user_name   = message_hash['touser']
    message.from_user_name = app.wx_id
    message.app_id         = app.id
    message.author_id      = current_user.id
    message.save!

    return message
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:to_user_name, :from_user_name, :create_time, :message_type, :content, :msg_id)
    end
end

wechat_service/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this wx_message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to_user_name %><br>
    <%= f.text_field :to_user_name %>
  </div>
  <div class="field">
    <%= f.label :from_user_name %><br>
    <%= f.text_field :from_user_name %>
  </div>
  <div class="field">
    <%= f.label :create_time %><br>
    <%= f.datetime_select :create_time %>
  </div>
  <div class="field">
    <%= f.label :message_type %><br>
    <%= f.text_field :message_type %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :msg_id %><br>
    <%= f.number_field :msg_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wechat_service/app/views/messages/edit.html.erb
<h1>Editing wx_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', wx_messages_path %>

wechat_service/app/views/messages/index.html.erb
<h1>Listing wx_users and messages</h1>
<input id="app_id" type="hidden" value="<%= params[:app_id] %>">
<ul class="users">
  <% @wx_users.each do |user| %>
    <li class="user-item"><a href="javascript: void(0);"><%= user.open_id %></a></li>
  <% end %>
</ul>

<ul class="messages">
  <div class="content"></div>
  <div class="sender">
    <input class="message-content">
    <input class="user-open-id" type="hidden" value="">
    <button class="send-message-btn">Submit</button>
  </div>
</ul>


<style type="text/css">
  .messages {display: none;}
  .messages .left{color: red;}
  .messages .right{color: blue;}
</style>

<script type="text/javascript">
  $(function(){
    $('ul.users').on('click', 'li.user-item>a', function(){
      $('.messages').show();
      var $messages = $('.messages>.content');
      $messages.text('');

      var user_open_id = $(this).text();
      var data = {app_id: $('#app_id').val(), user_open_id: user_open_id};
      $('.messages .user-open-id').val(user_open_id);
      $.get('/messages/all', data, function(result){
        var messages = result['messages'];
        var code = result['code'];
        if(code == 1){
          $('.notice').text('success');
          $.each(messages, function(_, msg){
            var content = msg['content'];
            var is_from_user = msg['from_user_name'] == user_open_id;
            var $li = build_message_li(content, is_from_user);
            $messages.append($li);
          });
        } else {
          $('.notice').text('faild');
        }
      });

      $('.messages').on('click', '.sender>.send-message-btn', function(){
        var $self = $(this);
        var $message = $self.siblings('.message-content');
        var message = $message.val();
        var user_open_id = $self.siblings('.user-open-id').val();
        var data = {user_open_id: user_open_id, message: message, app_id: $('#app_id').val()};
        $self.attr('disabled', 'disabled');
        $message.attr('disabled', 'disabled');

        $.post('/messages/send_message', data, function(result){
          $self.removeAttr('disabled');
          $message.removeAttr('disabled');

          var code = result['code'];
          if(code == 1){
            $message.val('');
            $('.notice').text('success');
            var $li = build_message_li(message, false);
            $('.messages>.content').append($li);
          } else {
            $('.notice').text('faild');
          }
        });
      });

      function build_message_li(message_content, is_from_user){
        var style_class = is_from_user ? 'left' : 'right';
        var $li = $('<li></li>');
        $li.addClass(style_class);
        $li.text(message_content);

        return $li;
      }
    });
  });
</script>

wechat_service/app/views/messages/new.html.erb
<h1>New wx_message</h1>

<%= render 'form' %>

<%= link_to 'Back', wx_messages_path %>

wechat_service/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>To user name:</strong>
  <%= @message.to_user_name %>
</p>

<p>
  <strong>From user name:</strong>
  <%= @message.from_user_name %>
</p>

<p>
  <strong>Create time:</strong>
  <%= @message.create_time %>
</p>

<p>
  <strong>Message type:</strong>
  <%= @message.message_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Msg:</strong>
  <%= @message.msg_id %>
</p>

<%= link_to 'Edit', edit_wx_message_path(@message) %> |
<%= link_to 'Back', wx_messages_path %>