wechat_service/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about_us'

  get 'home/contact_us'

  devise_for :users, class_name: "User"

  resources :apps
  resources :key_words
  resources :users
  resources :files
  resources :messages do
    collection do
      get 'all'
      post 'send_message'
    end
  end

  match 'wechat/:id' => 'wx#index', via: [:get, :post]
  match 'weixin_app' => 'wx#index', via: [:get, :post]

  root 'home#index'
end

wechat_service/app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  has_many :user_app_records
  has_many :apps, through: :user_app_records
  belongs_to :app
  belongs_to :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

wechat_service/app/controllers/users_controller.rb
class Wx::UsersController < ApplicationController
  before_action :set_wx_user, only: [:show, :edit, :update, :destroy]

  # GET /wx/users
  # GET /wx/users.json
  def index
    @wx_users = Wx::User.all
  end

  # GET /wx/users/1
  # GET /wx/users/1.json
  def show
  end

  # GET /wx/users/new
  def new
    @wx_user = Wx::User.new
  end

  # GET /wx/users/1/edit
  def edit
  end

  # POST /wx/users
  # POST /wx/users.json
  def create
    @wx_user = Wx::User.new(wx_user_params)

    respond_to do |format|
      if @wx_user.save
        format.html { redirect_to @wx_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @wx_user }
      else
        format.html { render :new }
        format.json { render json: @wx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wx/users/1
  # PATCH/PUT /wx/users/1.json
  def update
    respond_to do |format|
      if @wx_user.update(wx_user_params)
        format.html { redirect_to @wx_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @wx_user }
      else
        format.html { render :edit }
        format.json { render json: @wx_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wx/users/1
  # DELETE /wx/users/1.json
  def destroy
    @wx_user.destroy
    respond_to do |format|
      format.html { redirect_to wx_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wx_user
      @wx_user = Wx::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wx_user_params
      params.require(:wx_user).permit(:nick_name, :remark_name, :open_id, :app_id, :avatar_id, :description)
    end
end

wechat_service/app/views/users/_form.html.erb
<%= form_for(@wx_user) do |f| %>
  <% if @wx_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wx_user.errors.count, "error") %> prohibited this wx_user from being saved:</h2>

      <ul>
      <% @wx_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nick_name %><br>
    <%= f.text_field :nick_name %>
  </div>
  <div class="field">
    <%= f.label :remark_name %><br>
    <%= f.text_field :remark_name %>
  </div>
  <div class="field">
    <%= f.label :open_id %><br>
    <%= f.text_field :open_id %>
  </div>
  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.text_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :avatar_id %><br>
    <%= f.text_field :avatar_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wechat_service/app/views/users/edit.html.erb
<h1>Editing wx_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @wx_user %> |
<%= link_to 'Back', wx_users_path %>

wechat_service/app/views/users/index.html.erb
<h1>Listing wx_users</h1>

<table>
  <thead>
    <tr>
      <th>Nick name</th>
      <th>Remark name</th>
      <th>Open</th>
      <th>App</th>
      <th>Avatar</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wx_users.each do |wx_user| %>
      <tr>
        <td><%= wx_user.nick_name %></td>
        <td><%= wx_user.remark_name %></td>
        <td><%= wx_user.open_id %></td>
        <td><%= wx_user.app %></td>
        <td><%= wx_user.avatar %></td>
        <td><%= wx_user.description %></td>
        <td><%= link_to 'Show', wx_user %></td>
        <td><%= link_to 'Edit', edit_wx_user_path(wx_user) %></td>
        <td><%= link_to 'Destroy', wx_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_wx_user_path %>

wechat_service/app/views/users/new.html.erb
<h1>New wx_user</h1>

<%= render 'form' %>

<%= link_to 'Back', wx_users_path %>

wechat_service/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nick name:</strong>
  <%= @wx_user.nick_name %>
</p>

<p>
  <strong>Remark name:</strong>
  <%= @wx_user.remark_name %>
</p>

<p>
  <strong>Open:</strong>
  <%= @wx_user.open_id %>
</p>

<p>
  <strong>App:</strong>
  <%= @wx_user.app %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @wx_user.avatar %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wx_user.description %>
</p>

<%= link_to 'Edit', edit_wx_user_path(@wx_user) %> |
<%= link_to 'Back', wx_users_path %>