wechat_service/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about_us'

  get 'home/contact_us'

  devise_for :users, class_name: "User"

  resources :apps
  resources :key_words
  resources :users
  resources :files
  resources :messages do
    collection do
      get 'all'
      post 'send_message'
    end
  end

  match 'wechat/:id' => 'wx#index', via: [:get, :post]
  match 'weixin_app' => 'wx#index', via: [:get, :post]

  root 'home#index'
end

wechat_service/app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :icon_id %><br>
    <%= f.text_field :icon_id %>
  </div>
  <div class="field">
    <%= f.label :wx_id %><br>
    <%= f.text_field :wx_id %>
  </div>
  <div class="field">
    <%= f.label :app_id %><br>
    <%= f.text_field :app_id %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_area :secret %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_area :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wechat_service/app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

wechat_service/app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th>Wx</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |wx_app| %>
      <tr>
        <td><%= wx_app.name %></td>
        <td><%= wx_app.icon %></td>
        <td><%= wx_app.wx_id %></td>
        <td><%= link_to 'Show', wx_app %></td>
        <td><%= link_to 'Edit', edit_app_path(wx_app) %></td>
        <td><%= link_to 'Destroy', wx_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

wechat_service/app/views/apps/new.html.erb
<h1>New wx_app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

wechat_service/app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @app.icon %>
</p>

<p>
  <strong>Wx:</strong>
  <%= @app.wx_id %>
</p>

<a href="/key_words?app_id=<%= @app.id %>">KeyWords</a>
<a href="/messages?app_id=<%= @app.id %>">Messages</a>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>