wechat_service/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about_us'

  get 'home/contact_us'

  devise_for :users, class_name: "User"

  resources :apps
  resources :key_words
  resources :users
  resources :files
  resources :messages do
    collection do
      get 'all'
      post 'send_message'
    end
  end

  match 'wechat/:id' => 'wx#index', via: [:get, :post]
  match 'weixin_app' => 'wx#index', via: [:get, :post]

  root 'home#index'
end

wechat_service/app/models/file.rb
# encoding: utf-8
class DiskFile < ActiveRecord::Base
  def self.store_path
    "#{Rails.root}/files/"
  end

  def file_path

  end
end

wechat_service/app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :set_wx_file, only: [:show, :edit, :update, :destroy]

  # GET /wx/files
  # GET /wx/files.json
  def index
    @wx_files = File.all
  end

  # GET /wx/files/1
  # GET /wx/files/1.json
  def show
  end

  # GET /wx/files/new
  def new
    @wx_file = File.new
  end

  # GET /wx/files/1/edit
  def edit
  end

  # POST /wx/files
  # POST /wx/files.json
  def create
    @wx_file = File.new(file_params)

    respond_to do |format|
      if @wx_file.save
        format.html { redirect_to @wx_file, notice: 'File was successfully created.' }
        format.json { render :show, status: :created, location: @wx_file }
      else
        format.html { render :new }
        format.json { render json: @wx_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wx/files/1
  # PATCH/PUT /wx/files/1.json
  def update
    respond_to do |format|
      if @wx_file.update(file_params)
        format.html { redirect_to @wx_file, notice: 'File was successfully updated.' }
        format.json { render :show, status: :ok, location: @wx_file }
      else
        format.html { render :edit }
        format.json { render json: @wx_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wx/files/1
  # DELETE /wx/files/1.json
  def destroy
    @wx_file.destroy
    respond_to do |format|
      format.html { redirect_to wx_files_url, notice: 'File was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wx_file
      @wx_file = File.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_params
      params.require(:wx_file).permit(:file_name, :file_size, :mime_type, :digest, :description)
    end
end

wechat_service/app/views/files/_form.html.erb
<%= form_for(@wx_file) do |f| %>
  <% if @wx_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wx_file.errors.count, "error") %> prohibited this wx_file from being saved:</h2>

      <ul>
      <% @wx_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_size %><br>
    <%= f.number_field :file_size %>
  </div>
  <div class="field">
    <%= f.label :mime_type %><br>
    <%= f.text_field :mime_type %>
  </div>
  <div class="field">
    <%= f.label :digest %><br>
    <%= f.text_field :digest %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wechat_service/app/views/files/edit.html.erb
<h1>Editing wx_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @wx_file %> |
<%= link_to 'Back', wx_files_path %>

wechat_service/app/views/files/index.html.erb
<h1>Listing wx_files</h1>

<table>
  <thead>
    <tr>
      <th>File name</th>
      <th>File size</th>
      <th>Mime type</th>
      <th>Digest</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wx_files.each do |wx_file| %>
      <tr>
        <td><%= wx_file.file_name %></td>
        <td><%= wx_file.file_size %></td>
        <td><%= wx_file.mime_type %></td>
        <td><%= wx_file.digest %></td>
        <td><%= wx_file.description %></td>
        <td><%= link_to 'Show', wx_file %></td>
        <td><%= link_to 'Edit', edit_wx_file_path(wx_file) %></td>
        <td><%= link_to 'Destroy', wx_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File', new_wx_file_path %>

wechat_service/app/views/files/new.html.erb
<h1>New wx_file</h1>

<%= render 'form' %>

<%= link_to 'Back', wx_files_path %>

wechat_service/app/views/files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @wx_file.file_name %>
</p>

<p>
  <strong>File size:</strong>
  <%= @wx_file.file_size %>
</p>

<p>
  <strong>Mime type:</strong>
  <%= @wx_file.mime_type %>
</p>

<p>
  <strong>Digest:</strong>
  <%= @wx_file.digest %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wx_file.description %>
</p>

<%= link_to 'Edit', edit_wx_file_path(@wx_file) %> |
<%= link_to 'Back', wx_files_path %>